version: 2.1
orbs:
  nirmata: nirmata/nirmata-test@2.9.6
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - nirmata/add_catlog_app_command:
          app_name: "circlecitest1"
          yaml_file: "nginx.yml"
          nirmata_server: "nirmata.io"
          catalog : "circlecitest"
      - nirmata/deploy_command:
          app_name: "circlecitest1"
          app_name_deploy: "circlecitest1"
          nirmata_server: "nirmata.io"
          env_name: "circle-demo"
          catalog : "circlecitest"
      - run:
          command: echo $NIRMATA_API_KEY $api_key
      - nirmata/delete_catalog_app_command:
          app_name: "circlecitest1"
          nirmata_server: "nirmata.io"
          catalog : "circlecitest"
      - nirmata/delete_deployed_app_command:
          app_name: "circlecitest1"
          nirmata_server: "nirmata.io"
          env_name: "circle-demo"
