version: 2.1
orbs:
  nirmata: nirmata/nirmata@2.9.3
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - nirmata/add_catalog_app_command:
          app_name: "circlecitest1"
          yaml_file: "nginx.yml"
          nirmata_server: "nirmata.io"
          catalog : "circlecitest"
      - nirmata/create_env_command:
          env_name: "circle-demo3"
          cluster_name: "sam-test-conf"
          type: "large"
          nirmata_server: "nirmata.io"
      - nirmata/deploy_command:
          app_name: "circlecitest1"
          app_name_deploy: "circlecitest1"
          nirmata_server: "nirmata.io"
          env_name: "circle-demo3"
          catalog : "circlecitest"
      - run:
          command: sleep 30
      - nirmata/delete_catalog_app_command:
          app_name: "circlecitest1"
          nirmata_server: "nirmata.io"
          catalog : "circlecitest"
      - nirmata/delete_deployed_app_command:
          app_name: "circlecitest1"
          nirmata_server: "nirmata.io"
          env_name: "circle-demo3"
      - nirmata/delete_env_command:
          env_name: "circle-demo3"
          nirmata_server: "nirmata.io"
